#
# GiveCommand has 3 parameters: <player> (%s), <item> (%s), <amount> (%d)
GiveCommand: give %s %s %d
#
# TakeCommand has 2 parameters: <player> (%s), <totalprice> (%f)
TakeCommand: eco take %s %f
#
# YouNeedMoreMoneyMessage has 4 parameters: <money needed> (%f), <amount> (%d), <item> (%s), <current balance> (%f)
YouNeedMoreMoneyMessage: You need %.2f to buy %d %s. You have %.2f.
#
# SuccessfulPurchaseMessage has 2 parameters: <amount> (%d), <item> (%s)
SuccessfulPurchaseMessage: You successfully purchased %d item(s) of %s.¨
#
# CurrentBalanceMessage has 1 parameter: <balance> (%f)
CurrentBalanceMessage: Your balance is %.2f E-Coins.
